function [PN_name, set_of_places, set_of_trans,set_of_arcs] = ...
    definePetriNet() 

PN_name='Action Recognition Petri Net';
set_of_places={'RED', 'UFHG', 'USHG', 'ADH', 'RFS', 'RSS', 'RK', 'RW', 'DONE'};
set_of_trans={'RED_UHG', 'UHG_ADH', 'ADH_RS', 'RS_RK', 'RK_RW', 'RW_DONE'}; 
set_of_arcs={'RED', 'RED_UHG', 2, 'RED_UHG', 'UFHG', 1, ...
    'RED_UHG', 'USHG', 1, 'UFHG', 'UHG_ADH', 1, 'USHG', 'UHG_ADH', 1, ...
    'UHG_ADH', 'ADH', 2, 'ADH', 'ADH_RS', 2, 'ADH_RS', 'RFS', 1, ...
    'ADH_RS', 'RSS', 1, 'RFS', 'RS_RK', 1, 'RSS', 'RS_RK', 1, ...
    'RS_RK', 'RK', 2, 'RK', 'RK_RW', 2, 'RK_RW', 'RW', 2, ...
    'RW', 'RW_DONE', 2, 'RW_DONE', 'DONE', 2};    